[package]
name = "star_frame_idl"
description = "IDL definitions for Star Frame"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
verifier = []

[dependencies]